AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy API in Fargate with ALB and Nginx Sidecar for SSL/TLS and JWT validation.
Resources:
  # Define the ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-cluster

  # Define the Task Definition with both containers
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-task-family
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ECSExecutionRole
      TaskRoleArn: !Ref ECSTaskRole
      ContainerDefinitions:
        - Name: node-app
          Image: <your-node-app-image>
          Essential: true
          PortMappings:
            - ContainerPort: 3000
        - Name: nginx-sidecar
          Image: <your-nginx-sidecar-image>
          Essential: true
          PortMappings:
            - ContainerPort: 443

  # Define other resources (ALB, Target Group, Listener, Security Groups, IAM Roles, etc.)
